-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 12:38:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecomlocal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecomlocal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecomlocal` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecomlocal` ;

-- -----------------------------------------------------
-- Table `ecomlocal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`users` (
                                                 `id` INT(11) NOT NULL AUTO_INCREMENT,
                                                 `id_user` INT(11) NULL DEFAULT NULL,
                                                 `email` VARCHAR(45) NULL DEFAULT NULL,
                                                 `password` VARCHAR(12) NULL DEFAULT NULL,
                                                 `role` VARCHAR(12) NULL DEFAULT NULL COMMENT 'admin/delivery/agent',
                                                 `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                 `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                 PRIMARY KEY (`id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ecomlocal`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`areas` (
                                                 `id_area` INT NOT NULL AUTO_INCREMENT,
                                                 `area` VARCHAR(45) NULL,
                                                 `shipping` INT NULL,
                                                 `return` INT NULL,
                                                 `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                 `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                 PRIMARY KEY (`id_area`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`confirmers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`confirmers`
(
  `id_confirmer`  INT         NOT NULL AUTO_INCREMENT,
  `first_name`    VARCHAR(45) NULL,
  `last_name`     VARCHAR(45) NULL,
  `phone_number`  VARCHAR(45) NULL,
  `CIN`           VARCHAR(45) NULL,
  `address`       VARCHAR(45) NULL,
  `profile_pic`   VARCHAR(45) NULL,
  `price_confirm` INT(11)     NULL,
  `price_cancel`  INT(11)     NULL,
  `created_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_confirmer`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecomlocal`.`deliverers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`deliverers` (
                                                      `id_deliverer` INT NOT NULL AUTO_INCREMENT,
                                                      `first_name` VARCHAR(45) NULL,
                                                      `last_name` VARCHAR(45) NULL,
                                                      `phone_number` VARCHAR(45) NULL,
                                                      `CIN` VARCHAR(45) NULL,
                                                      `id_area` INT NOT NULL,
                                                      `address` VARCHAR(45) NULL,
                                                      `profile_pic` VARCHAR(45) NULL,
                                                      `price_delivered` INT(11) NULL,
                                                      `price_returned` INT(11) NULL,
                                                      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                      `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                      PRIMARY KEY (`id_deliverer`),
                                                      INDEX `fk_deliverers_cities1_idx` (`id_area` ASC),
                                                      CONSTRAINT `fk_deliverers_cities1`
                                                        FOREIGN KEY (`id_area`)
                                                          REFERENCES `ecomlocal`.`areas` (`id_area`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`deliverer_packs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`deliverer_packs` (
                                                           `id_deliverer_pack` INT NOT NULL AUTO_INCREMENT,
                                                           `id_deliverer` INT(11) NULL,
                                                           `created_date` DATE NULL,
                                                           `label` VARCHAR(45) NULL,
                                                           `status` VARCHAR(45) NULL DEFAULT 'pending/open/done',
                                                           `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                           `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                           PRIMARY KEY (`id_deliverer_pack`),
                                                           INDEX `fk_deliverer_packs_deliverers1_idx` (`id_deliverer` ASC),
                                                           CONSTRAINT `fk_deliverer_packs_deliverers1`
                                                             FOREIGN KEY (`id_deliverer`)
                                                               REFERENCES `ecomlocal`.`deliverers` (`id_deliverer`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`products` (
                                                    `id_product` INT NOT NULL AUTO_INCREMENT,
                                                    `thumbnail` VARCHAR(45) NULL,
                                                    `title` VARCHAR(135) NULL,
                                                    `sub_title` VARCHAR(135) NULL,
                                                    `description` TEXT NULL,
                                                    `price` DECIMAL(10,2) NULL,
                                                    `compared_price` INT NULL,
                                                    `has_variants` BLOB NULL DEFAULT false,
                                                    `quantity` INT NULL,
                                                    `type` VARCHAR(45) NULL,
                                                    `is_published` BLOB NULL DEFAULT false,
                                                    `meta_title` VARCHAR(255) NULL,
                                                    `meta_description` TEXT NULL,
                                                    `meta_keywords` VARCHAR(255) NULL,
                                                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (`id_product`))
  ENGINE = InnoDB;

ALTER TABLE products
  ADD COLUMN `sub_title` VARCHAR(135) NULL;

-- -----------------------------------------------------
-- Table `ecomlocal`.`clients_packs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`clients_packs` (
                                                         `id_client_pack` INT NOT NULL AUTO_INCREMENT,
                                                         `id_area` INT NOT NULL,
                                                         `client_name` VARCHAR(45) NULL,
                                                         `client_phone` VARCHAR(45) NULL,
                                                         `client_address` VARCHAR(135) NULL,
                                                         `label` VARCHAR(135) NULL,
                                                         `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                         `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                         PRIMARY KEY (`id_client_pack`),
                                                         INDEX `fk_clients_packs_cities1_idx` (`id_area` ASC),
                                                         CONSTRAINT `fk_clients_packs_cities1`
                                                           FOREIGN KEY (`id_area`)
                                                             REFERENCES `ecomlocal`.`areas` (`id_area`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`variants` (
                                                    `id_variant` INT NOT NULL AUTO_INCREMENT,
                                                    `variant` VARCHAR(45) NULL,
                                                    `quantity` INT NULL,
                                                    `price` INT NULL,
                                                    `image` VARCHAR(45) NULL,
                                                    `id_product` INT,
                                                    PRIMARY KEY (`id_variant`),
                                                    UNIQUE INDEX `id_variant_UNIQUE` (`id_variant` ASC),
                                                    INDEX `fk_variants_products1_idx` (`id_product` ASC),
                                                    CONSTRAINT `fk_variants_products1`
                                                      FOREIGN KEY (`id_product`)
                                                        REFERENCES `ecomlocal`.`products` (`id_product`)
                                                        ON DELETE SET NULL
                                                        ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`orders` (
                                                  `id_order` INT NULL AUTO_INCREMENT,
                                                  `id_product` INT,
                                                  `order_date` DATE NULL,
                                                  `items_quantity` INT(11) NULL,
                                                  `id_deliverer_pack` INT(11) NULL,
                                                  `id_client_pack` INT NOT NULL,
                                                  `id_variant` INT NULL,
                                                  `total` INT NULL,
                                                  `status` VARCHAR(45) NULL DEFAULT 'Pending',
                                                  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                  PRIMARY KEY (`id_order`),
                                                  INDEX `fk_orders_deliverer_packs1_idx` (`id_deliverer_pack` ASC),
                                                  INDEX `fk_orders_products1_idx` (`id_product` ASC),
                                                  INDEX `fk_orders_clients_packs1_idx` (`id_client_pack` ASC),
                                                  INDEX `fk_orders_variants1_idx` (`id_variant` ASC),
                                                  CONSTRAINT `fk_orders_deliverer_packs1`
                                                    FOREIGN KEY (`id_deliverer_pack`)
                                                      REFERENCES `ecomlocal`.`deliverer_packs` (`id_deliverer_pack`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_orders_products1`
                                                    FOREIGN KEY (`id_product`)
                                                      REFERENCES `ecomlocal`.`products` (`id_product`)
                                                      ON DELETE SET NULL
                                                      ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_orders_clients_packs1`
                                                    FOREIGN KEY (`id_client_pack`)
                                                      REFERENCES `ecomlocal`.`clients_packs` (`id_client_pack`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_orders_variants1`
                                                    FOREIGN KEY (`id_variant`)
                                                      REFERENCES `ecomlocal`.`variants` (`id_variant`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`shop` (
                                                `name` VARCHAR(45) NULL,
                                                `logo` VARCHAR(45) NULL)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`product_images` (
                                                          `id_product_image` INT NOT NULL AUTO_INCREMENT,
                                                          `image` VARCHAR(45) NULL,
                                                          `alt` VARCHAR(45) NULL,
                                                          `id_product` INT,
                                                          PRIMARY KEY (`id_product_image`),
                                                          INDEX `fk_product_images_products1_idx` (`id_product` ASC),
                                                          CONSTRAINT `fk_product_images_products1`
                                                            FOREIGN KEY (`id_product`)
                                                              REFERENCES `ecomlocal`.`products` (`id_product`)
                                                              ON DELETE SET NULL
                                                              ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`categories` (
                                                      `id_category` INT NOT NULL AUTO_INCREMENT,
                                                      `category` VARCHAR(45) NULL,
                                                      `thumbnail` VARCHAR(45) NULL,
                                                      `description` VARCHAR(135) NULL,
                                                      `is_published` BLOB NULL DEFAULT false,
                                                      PRIMARY KEY (`id_category`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`products_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`products_categories` (
                                                               `id` INT NOT NULL AUTO_INCREMENT,
                                                               `id_product` INT,
                                                               `id_category` INT NOT NULL,
                                                               PRIMARY KEY (`id`),
                                                               INDEX `fk_products_categories_categories1_idx` (`id_category` ASC),
                                                               CONSTRAINT `fk_products_categories_products1`
                                                                 FOREIGN KEY (`id_product`)
                                                                   REFERENCES `ecomlocal`.`products` (`id_product`)
                                                                   ON DELETE SET NULL
                                                                   ON UPDATE NO ACTION,
                                                               CONSTRAINT `fk_products_categories_categories1`
                                                                 FOREIGN KEY (`id_category`)
                                                                   REFERENCES `ecomlocal`.`categories` (`id_category`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomlocal`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`deliveries` (
                                                              `id_delivery` INT NOT NULL AUTO_INCREMENT,
                                                              `id_order` INT NULL COMMENT 'Dashboard / Client / Deliverer',
                                                              `id_deliverer` INT NULL,
                                                              `role_deliverer` VARCHAR(45) NULL COMMENT 'Dashboard / Deliverer',
                                                              `delivery_status` VARCHAR(45) NULL COMMENT 'Pending / Processing / Confirm / unreachable / Cancel / Deliver',
                                                              `comment` VARCHAR(45) NULL,
                                                              `id_invoice` INT NULL,
                                                              `isPaid` BIT DEFAULT false,
                                                              `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                              `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                              PRIMARY KEY (`id_delivery`),
                                                              CONSTRAINT `fk_deliveries_deliverers1`
                                                                FOREIGN KEY (`id_deliverer`)
                                                                  REFERENCES `ecomlocal`.`deliverers` (`id_deliverer`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                              CONSTRAINT `fk_deliveries_orders1`
                                                                FOREIGN KEY (`id_order`)
                                                                  REFERENCES `ecomlocal`.`orders` (`id_order`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                              CONSTRAINT `fk_deliveries_invoices1`
                                                                FOREIGN KEY (`id_invoice`)
                                                                  REFERENCES `ecomlocal`.`invoices` (`id_invoice`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecomlocal`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`confirmations` (
                                                      `id_confirmation` INT NOT NULL AUTO_INCREMENT,
                                                      `id_order` INT NULL,
                                                      `id_confirmer` INT NULL,
                                                      `role_confirmer` VARCHAR(45) NULL COMMENT 'Dashboard / Confirmer',
                                                      `confirmation_status` VARCHAR(45) NULL COMMENT 'Confirm / Cancel',
                                                      `comment` VARCHAR(45) NULL,
                                                      `id_invoice` INT NULL,
                                                      `isPaid` BIT DEFAULT false,
                                                      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                      `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                      PRIMARY KEY (`id_confirmation`),
                                                      CONSTRAINT `fk_confirmations_confirmers1`
                                                        FOREIGN KEY (`id_confirmer`)
                                                          REFERENCES `ecomlocal`.`confirmers` (`id_confirmer`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_confirmations_orders1`
                                                        FOREIGN KEY (`id_order`)
                                                          REFERENCES `ecomlocal`.`orders` (`id_order`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_confirmations_invoices1`
                                                        FOREIGN KEY (`id_invoice`)
                                                          REFERENCES `ecomlocal`.`invoices` (`id_invoice`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecomlocal`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`invoices` (
                                                            `id_invoice` INT NOT NULL AUTO_INCREMENT,
                                                            `id_user` INT NULL,
                                                            `full_name` VARCHAR(45) NULL,
                                                            `type` VARCHAR(10) NULL COMMENT 'client / deliverer',
                                                            `credit` INT NULL,
                                                            `bill` INT NULL,
                                                            `creation_date` DATETIME NULL,
                                                            `comment` VARCHAR(100) NULL,
                                                            `status` VARCHAR(10) NULL DEFAULT 'unPaid' COMMENT 'Paid / unPaid',
                                                            PRIMARY KEY (`id_invoice`))
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ecomlocal`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomlocal`.`notifications` (
                                                                 `id_notification` INT NOT NULL AUTO_INCREMENT,
                                                                 `id_target` INT NULL,
                                                                 `target` VARCHAR(45) NULL COMMENT 'Client / Deliverer / Dashboard',
                                                                 `content` VARCHAR(45) NULL,
                                                                 `datetime` DATETIME NULL,
                                                                 `is_open` BIT NULL DEFAULT false,
                                                                 PRIMARY KEY (`id_notification`))
  ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ecomlocal`.`config` (
                                                          `id_config` INT NOT NULL AUTO_INCREMENT,
                                                          `logo` VARCHAR(45) NULL DEFAULT 'default',
                                                          `name` VARCHAR(45) NULL DEFAULT 'default',
                                                          PRIMARY KEY (`id_config`))
  ENGINE = InnoDB;
insert into config (logo, name) value ('logo.png', 'Default');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
